steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-connect-db', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/test-connect-db']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'test-connect-db'
      - '--image'
      - 'gcr.io/$PROJECT_ID/test-connect-db'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast2'
      - '--allow-unauthenticated'
      # - '--vpc-connector'
      # - 'projects/$PROJECT_ID/locations/asia-southeast2/connectors/test-connect-db'
